### ISSUE TITLE
Additional reserved words

### ISSUE THREAD

**Issue by olistic** [mvila/reserved-usernames#2]
Hello! I found [this article](https://ldpreload.com/blog/names-to-reserve) when researching about reserved usernames. From the article:

> For many websites with user-provided content, like Twitter, Facebook, or GitHub, user-chosen usernames become part of the URL at top level (https://twitter.com/geofft, https://github.com/geofft). If you're building a website like this, the easiest approach is to restrict these usernames as if they were hostnames. This has two advantages: the first is that it's easy to launch a hostname-based system later (e.g. GitHub Pages now supports geofft.github.io) if you know that all your usernames are valid hostnames.

Would you consider adding the words suggested in the article that are missing in your list? Those would be:

```
abuse
autoconfig
broadcasthost
isatap
localdomain
localhost
mailer-daemon
mis
nobody
noc
noreply
no-reply
usenet
uucp
wpad
```

The entire list can be found [here](https://ldpreload.com/files/names-to-reserve.txt).

Thanks!

**Comment by mvila** [comment]
Thanks @olistic! I have added the words you suggested. :)
